evalengine: Support built-in MySQL function for CONV function
vitessio/vitess pull request #11566
Opened 2022-10-24 16:43 UTC by Weijun-H

Signed-off-by: Weijun-H <huangweijun1001@gmail.com>

## Description
The following functions will be supported
- [x]  CONV()

## Related Issue(s)
- #9647 

## Checklist

-   [ ] "Backport me!" label has been added if this change should be backported
-   [x] Tests were added or are not required
-   [x] Documentation was added or is not required

## Deployment Notes

2022-10-25 16:33 UTC, vmg requested changes
This is not a great implementation @Weijun-H. You need to put more thought into this. If you widen your set of integration test cases you'll see that it breaks at the seams very easily.

2022-10-25 16:33 UTC, vmg commented on go/vt/vtgate/evalengine/string.go
> +	if inarg.isNull() || fromBase.isNull() || toBase.isNull() || fromBase.int64() < 2 || fromBase.int64() > 36 || toBase.int64() < 2 || toBase.int64() > 36 {
You cannot call `int64` over and over; `toBase` and `fromBase` need to be converted to their integer forms before they can be checked.

2022-10-25 16:33 UTC, vmg commented on go/vt/vtgate/evalengine/string.go
> +	inarg.makeSignedIntegral()
You don't want a signed integral for `inarg`. You want the raw textual bytes so you can process them.

2022-10-25 16:33 UTC, vmg commented on go/vt/vtgate/evalengine/string.go
> +	num, _ := strconv.ParseInt(fmt.Sprint(inarg.int64()), int(fromBase.int64()), 64)
MySQL handles overflow with saturation, not 0-truncation.

Try:

```
+-----------------------------------------------------------------------------------------------------------------------+
| conv(99999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999, 10, 2) |
+-----------------------------------------------------------------------------------------------------------------------+
| 1111111111111111111111111111111111111111111111111111111111111111                                                      |
+-----------------------------------------------------------------------------------------------------------------------+
```

2022-10-25 16:33 UTC, vmg commented on go/vt/vtgate/evalengine/string.go
> +	result.makeTextual(env.DefaultCollation)
Absolutely no point on calling `makeTextual` after `setRaw`. Particularly if you're going to change the collation. You can set the desired collation directly on the previous call.

2022-10-25 16:33 UTC, vmg commented on go/vt/vtgate/evalengine/string.go
> +
Missing typecheck for `args[2]`.

2022-10-25 16:33 UTC, vmg commented on go/vt/vtgate/evalengine/integration/string_fun_test.go
> +	}
This is a very limited set of test cases. You need to widen this. Particularly important: hex literals.

2022-11-03 12:40 UTC, GuptaManan100 requested changes
I actually checked `'+10'` and it fails.
I also checked and `'10-9+10'` also fails. You aren't supposed to evaluate the string in the conv function. Just use the raw bytes and interpret them in the given base. Your output for this string is `9` (which I don't understand how you got to anyways, `11` I could understand) but MySQL just says 10, because it ignores everything after the - sign.

2022-11-03 12:40 UTC, GuptaManan100 commented on go/vt/vtgate/evalengine/integration/string_fun_test.go
> +	}
These still aren't strong enough cases. What happens if we have a `+` in the beginning? What if we have 2 of those in the beginning? What if it is a string with a + and not a number?

2022-11-03 12:40 UTC, GuptaManan100 commented on go/vt/vtgate/evalengine/string.go
> +	}
I don't think the checks `inarg2.isNull()` or `inarge3.isNull()` is required. The values of fromBase and toBase would be 0 if they were null respectively, so the condition would still be true.

2022-11-03 12:40 UTC, GuptaManan100 commented on go/vt/vtgate/evalengine/string.go
> +	}
Is there any specific reason why you need the float type as a separate case?

2022-11-03 12:40 UTC, GuptaManan100 commented on go/vt/vtgate/evalengine/string.go
> +	for _, num := range re.FindAllString(rawString, -1) {
Why do you need all substring matches? Don't you only need the first one? In what case would have more than 1 matches?

2022-11-08 09:36 UTC, GuptaManan100 commented
In my opinion, the best way to do the conversion is to do it in two parts. You should convert using from_base and handle the behaviour of a negative from_base value. Once that conversion is complete, then do a second conversion into the to_base value and also handle the negative values there.
From what I have observed from MySQL behaviour is that, if the from_base is negative, then your input is treated as a signed integer, so the limits of int64 apply. Otherwise, the limits of uint64 apply!
```
mysql [localhost:8026] {msandbox} (test) > SELECT CONV(1000000000000000000000000000000,10,10);
+---------------------------------------------+
| CONV(1000000000000000000000000000000,10,10) |
+---------------------------------------------+
| 18446744073709551615                        |
+---------------------------------------------+
1 row in set, 1 warning (0.00 sec)

mysql [localhost:8026] {msandbox} (test) > SELECT CONV(1000000000000000000000000000000,-10,10);
+----------------------------------------------+
| CONV(1000000000000000000000000000000,-10,10) |
+----------------------------------------------+
| 9223372036854775807                          |
+----------------------------------------------+
1 row in set, 1 warning (0.00 sec)
```

and then if your to_base is negative, then your output can be signed - 
```

mysql [localhost:8026] {msandbox} (test) > SELECT CONV(-1,-10,10);
+----------------------+
| CONV(-1,-10,10)      |
+----------------------+
| 18446744073709551615 |
+----------------------+
1 row in set (0.00 sec)

mysql [localhost:8026] {msandbox} (test) > SELECT CONV(-1,-10,-10);
+------------------+
| CONV(-1,-10,-10) |
+------------------+
| -1               |
+------------------+
1 row in set (0.01 sec)
```

2022-11-08 09:39 UTC, GuptaManan100 commented
These are all worthwhile test cases to have -
```sql
mysql [localhost:8026] {msandbox} (test) > SELECT CONV(10000000000000000000000000,-10,-10);
+------------------------------------------+
| CONV(10000000000000000000000000,-10,-10) |
+------------------------------------------+
| 9223372036854775807                      |
+------------------------------------------+
1 row in set, 1 warning (0.00 sec)

mysql [localhost:8026] {msandbox} (test) > SELECT CONV(10000000000000000000000000,-10,10);
+-----------------------------------------+
| CONV(10000000000000000000000000,-10,10) |
+-----------------------------------------+
| 9223372036854775807                     |
+-----------------------------------------+
1 row in set, 1 warning (0.00 sec)

mysql [localhost:8026] {msandbox} (test) > SELECT CONV(10000000000000000000000000,10,10);
+----------------------------------------+
| CONV(10000000000000000000000000,10,10) |
+----------------------------------------+
| 18446744073709551615                   |
+----------------------------------------+
1 row in set, 1 warning (0.00 sec)

mysql [localhost:8026] {msandbox} (test) > SELECT CONV(10000000000000000000000000,10,-10);
+-----------------------------------------+
| CONV(10000000000000000000000000,10,-10) |
+-----------------------------------------+
| -1                                      |
+-----------------------------------------+
1 row in set, 1 warning (0.00 sec)
```

2022-11-09 15:22 UTC, Weijun-H commented on go/vt/vtgate/evalengine/string.go
> +	inarg.makeTextualAndConvert(env.DefaultCollation)
> You can just extract the collation from inarg and change the collation and then type cast the result directly using that.

I have no idea how to do in this way.

2022-12-19 01:31 UTC, closed without merging