Prevent etcd topology locks from silently expiring.
vitessio/vitess pull request #11794
Opened 2022-11-22 22:03 UTC by arthurschreiber

## Description

If the context passed in to the `Lock` function was canceled / timed out / had exceeded its deadline _after_ the lock was acquired, Vitess silently stopped sending keepAlive requests to etcd, and the lock would be lost after reaching the lease ttl.

This change prevents that from happening by using a fresh context struct for the `KeepAlive` call, which is canceled once the lock is released.

## Related Issue(s)

N/A

## Checklist

-   [ ] "Backport to:" labels have been added if this change should be back-ported
-   [ ] Tests were added or are not required
-   [ ] Documentation was added or is not required

## Deployment Notes

2022-11-22 22:08 UTC, arthurschreiber commented
I think this _should_ be backported, as without this change locking with an etcd2 is potentially unsafe. 🤔

2022-11-22 22:56 UTC, arthurschreiber commented
Some more context - we encountered this while using VDiff2. When a vdiff workflow was stopped / resumed, we'd sometimes end with the source and target streams using _different_ snapshots, or vreplication streams ending up in weird states. The VDiff code was using a keyspace lock to prevent concurrent modification of `vreplication` tables, but _somehow_ we saw that concurrent modification was happening anyway.

Digging deeper, we noticed that stopping a vdiff workflow is implemented using a cancelable context, and that cancellation would eventually propagate down to the context passed to `Lock`. If the context was canceled _after_ acquiring the lock, the lock was released _before_ the call to `Unlock`, and the call to `Unlock` failed with:

```
E1121 15:00:14.185298   33058 table_differ.go:105] UnlockKeyspace issues_pull_requests_ks failed: <nil>
```

Due to a separate bug in the VDiff code, we can't see the unlock failure message here (only `<nil>`), but I'm pretty sure the unlocking failed because the lock was no longer held.

2022-11-24 08:21 UTC, GuptaManan100 commented
@arthurschreiber Could you create an issue and link it to this PR? All bug fixes in Vitess now require having an associated issue describing the bug.

2022-11-24 09:28 UTC, arthurschreiber commented
@GuptaManan100 I added https://github.com/vitessio/vitess/issues/11811.

2022-11-25 05:41 UTC, GuptaManan100 requested changes
I don’t think that the proposed fix for the bug described in the PR is correct. From what I understand, the implicit unlock seems to be the proper behavior. What I think is incorrect is the assumption in the vdiff code to assume that the lock is held even after the context expires. In ERS and PRS we have explicit checks to see if we still hold the lock, for this reason, otherwise, those checks won’t be required since our context could expire and we would continue to hold the lock.

There would be no safety mechanism either if we allowed this change. Like a process gets a lock. For some reason it gets stuck (deadlocked or something else). The context expires but we won’t let go of the lock leading to the entire system being stuck. 
I believe that the lock being released on context expiry isn't just etcd topology specific but a decision decision to guarantee forward progress in face of deadlocks (if any)

2023-01-05 01:33 UTC, closed without merging