Use a left join to make sure that tables with tablespace=innodb_system are included in the schema
vitessio/vitess pull request #12672
Opened 2023-03-20 17:45 UTC by kovyrin

## Description

To make sure the behaviour of the schema engine is the same for 5.7 and 8.0 in terms of handling of tables that have innodb tablespace set to innodb_system (those are not included in `information_schema.innodb_tablespaces`). This should make sure that vstreamer works as expected when some of the tables in a keyspace have been created with `tablespace innodb_system` option (because of https://bugs.mysql.com/bug.php?id=110383 or some other reason).

This issue exists in 14.x and the fix needs backporting AFAIU.

## Related Issue(s)

Fixes #12669

## Checklist

-   [ ] "Backport to:" labels have been added if this change should be back-ported
-   [ ] Tests were added or are not required
-   [ ] Did the new or modified tests pass consistently locally and on the CI
-   [ ] Documentation was added or is not required

2023-03-20 19:23 UTC, kovyrin commented
Not sure how to (or if I should) write a test for this, but tested it locally as follows:

1. Checked out this branch locally
2. Built Vitess
3. Deployed a test cluster locally
4. Created a test table in the commerce keyspace
5. Used grpcurl to connect to vstream API
6. Inserted data into the test table
7. Observed vstream responses in the grpcurl console

2023-03-20 19:39 UTC, mattlord approved these changes
Makes sense to me -- we want all tables, even if they don't have an associated dedicated tablespace (I would guess this is also an issue when using [general tablespaces](https://dev.mysql.com/doc/refman/en/general-tablespaces.html), as that's what the `system_tablespace` is). Thank you for this, @kovyrin ! ❤️

2023-03-20 19:43 UTC, mattlord reviewed
I think that we should add a test for this. One which fails on main and passes here.

2023-03-20 19:54 UTC, mattlord requested changes
We could add a minimal test here by e.g. creating the product table here in the system_tablespace: https://github.com/vitessio/vitess/blob/main/go/test/endtoend/vreplication/config_test.go#L37

@kovyrin make sense? Please let me know if you need any help.

2023-03-20 21:30 UTC, kovyrin commented
Modified the customer schema to use the system tablespace. This should cover the change on 8.0 (breaks on main).

2023-03-21 02:01 UTC, mattlord approved these changes

2023-03-21 14:16 UTC, harshit-gangal reviewed
how do we get size for those tables?

2023-03-25 05:10 UTC, mattlord commented
> how do we get size for those tables?

Good question! We'd need to do more (although I'd argue that recognizing the table w/o a known size is still an improvement over not being aware of it at all). 

This is one possibility:
```
## Current query 
mysql> SELECT t.table_name, t.table_type, UNIX_TIMESTAMP(t.create_time), t.table_comment,  SUM(i.file_size) as storage_size,  SUM(i.allocated_s
ize)  FROM information_schema.tables t LEFT JOIN information_schema.innodb_tablespaces i ON i.name LIKE CONCAT(database(), '/%') AND (i.name =
CONCAT(t.table_schema, '/', t.table_name) OR i.name LIKE CONCAT(t.table_schema, '/', t.table_name, '#p#%'))  WHERE t.table_schema = database()
 GROUP BY t.table_name, t.table_type, t.create_time, t.table_comment\G
*************************** 1. row ***************************
                   TABLE_NAME: corder
                   TABLE_TYPE: BASE TABLE
UNIX_TIMESTAMP(t.create_time): 1679718422
                TABLE_COMMENT:
                 storage_size: 114688
        SUM(i.allocated_size): 114688
*************************** 2. row ***************************
                   TABLE_NAME: customer
                   TABLE_TYPE: BASE TABLE
UNIX_TIMESTAMP(t.create_time): 1679718422
                TABLE_COMMENT:
                 storage_size: 114688
        SUM(i.allocated_size): 114688
*************************** 3. row ***************************
                   TABLE_NAME: test1
                   TABLE_TYPE: BASE TABLE
UNIX_TIMESTAMP(t.create_time): 1679719746
                TABLE_COMMENT:
                 storage_size: NULL
        SUM(i.allocated_size): NULL
*************************** 4. row ***************************
                   TABLE_NAME: ti
                   TABLE_TYPE: BASE TABLE
UNIX_TIMESTAMP(t.create_time): 1679720520
                TABLE_COMMENT:
                 storage_size: 688128
        SUM(i.allocated_size): 688128
4 rows in set (0.01 sec)

## New Query
mysql> SELECT t.table_name, t.table_type, UNIX_TIMESTAMP(t.create_time), t.table_comment, IFNULL(SUM(i.file_size), (select data_length+index_length from information_schema.tables where table_name=t.table_name)) as storage_size,  SUM(i.allocated_size)  FROM information_schema.tables t LEFT JOIN information_schema.innodb_tablespaces i ON i.name LIKE CONCAT(database(), '/%') AND (i.name = CONCAT(t.table_schema, '/', t.table_name) OR i.name LIKE CONCAT(t.table_schema, '/', t.table_name, '#p#%'))  WHERE t.table_schema = database()  GROUP BY t.table_name, t.table_type, t.create_time, t.table_comment\G
*************************** 1. row ***************************
                   TABLE_NAME: corder
                   TABLE_TYPE: BASE TABLE
UNIX_TIMESTAMP(t.create_time): 1679718422
                TABLE_COMMENT:
                 storage_size: 114688
        SUM(i.allocated_size): 114688
*************************** 2. row ***************************
                   TABLE_NAME: customer
                   TABLE_TYPE: BASE TABLE
UNIX_TIMESTAMP(t.create_time): 1679718422
                TABLE_COMMENT:
                 storage_size: 114688
        SUM(i.allocated_size): 114688
*************************** 3. row ***************************
                   TABLE_NAME: test1
                   TABLE_TYPE: BASE TABLE
UNIX_TIMESTAMP(t.create_time): 1679719746
                TABLE_COMMENT:
                 storage_size: 16384
        SUM(i.allocated_size): NULL
*************************** 4. row ***************************
                   TABLE_NAME: ti
                   TABLE_TYPE: BASE TABLE
UNIX_TIMESTAMP(t.create_time): 1679720520
                TABLE_COMMENT:
                 storage_size: 688128
        SUM(i.allocated_size): 688128
4 rows in set (0.00 sec)
```

2023-03-27 11:53 UTC, merged