vtctldclient: Add missing new backup option
vitessio/vitess pull request #13543
Opened 2023-07-18 15:22 UTC by dbussink

This was missed in the original PR in #13449 

## Related Issue(s)

Missed in #13449 which addressed https://github.com/vitessio/vitess/issues/13448, also see https://github.com/vitessio/website/pull/1540#discussion_r1266929371

## Checklist

-   [ ] "Backport to:" labels have been added if this change should be back-ported
-   [ ] Tests were added or are not required
-   [ ] Did the new or modified tests pass consistently locally and on the CI
-   [ ] Documentation was added or is not required

## Deployment Notes

2023-07-18 17:50 UTC, ajm188 approved these changes
you can then run (in the vitessio/website repo) something like `VITESS_DIR=~/dev/vitess VTCTLDCLIENT_VERSION_PAIRS="main:18.0,release-16.0:16.0,upstream/release-17.0:17.0" make vtctldclient-docs` after merging/backporting to get the docs regenerated

2023-07-19 14:45 UTC, mattlord requested changes

2023-07-19 14:45 UTC, mattlord commented on go/cmd/vtctldclient/command/backups.go
> +		Use:                   "Backup [--concurrency <concurrency>] [--allow-primary] [--upgrade_safe] <tablet_alias>",
All new flags should use dashes rather than underscores. It looks like the flag actually is using a dash, but the use line is wrong.

2023-07-19 15:10 UTC, mattlord approved these changes

2023-07-20 07:14 UTC, merged