Update v17 Release notes with a Breaking Change
vitessio/vitess pull request #14215
Opened 2023-10-09 16:28 UTC by MrFabio

## Description

Added a note to the Breaking Changes for the updated version of `init_db.sql`

## Related Issue(s)

https://github.com/vitessio/vitess/pull/12206

## Checklist

-   [ ] "Backport to:" labels have been added if this change should be back-ported
-   [x] Tests were added or are not required
-   [ ] Did the new or modified tests pass consistently locally and on the CI
-   [x] Documentation was added or is not required

## Deployment Notes

None.

2023-10-09 16:37 UTC, mattlord approved these changes
LGTM. Thanks, @MrFabio ! I've made the same change in the GitHub release page: https://github.com/vitessio/vitess/releases/tag/v17.0.0

2023-10-09 17:29 UTC, frouioui requested changes
Hello @MrFabio, thank you for this contribution. Can you also edit the `release_notes.md` file please?

Note to maintainers: we will need to update the release notes on the UI once this is merged.

2023-10-09 20:19 UTC, MrFabio commented
> Hello @MrFabio, thank you for this contribution. Can you also edit the `release_notes.md` file please?
> 
> Note to maintainers: we will need to update the release notes on the UI once this is merged. EDIT: [#14215 (review)](https://github.com/vitessio/vitess/pull/14215#pullrequestreview-1664921469) @mattlord did it.

Done

2023-10-09 23:06 UTC, frouioui approved these changes
LGTM, thank you!

2023-10-10 04:10 UTC, GuptaManan100 approved these changes

2023-10-10 04:10 UTC, merged