feature: stop all kinds of expressions from cnf-exploding
vitessio/vitess pull request #14585
Opened 2023-11-22 16:53 UTC by systay

## Description
In a recent change (#14560) we fixed a bug in the CNF rewriter that stopped it from rewriting a lot of cases.
Unfortunately, we succeeded too well, and the newly rewritten expressions are timing out in expression fuzzing on CI. This is because CNF rewriting in some situations result in huge outputs (see [Wikipedia](https://en.wikipedia.org/wiki/Conjunctive_normal_form#Conversion_into_CNF))

This PR stops the rewriting once the produced expression has grown to 10 times the size of the original expression. 

## Related Issue(s)
Fixes #14569

## Checklist
-   [x] "Backport to:" labels have been added if this change should be back-ported
-   [x] Tests were added or are not required
-   [x] Did the new or modified tests pass consistently locally and on the CI
-   [x] Documentation was added or is not required

2023-11-22 17:02 UTC, vmg requested changes
I think we need to look at benchmarks for this @systay, the O complexity of this new code is pathological because after each rewrite, you need to walk the whole AST to count the nodes.

Since we control the rewrite patterns, I think it would be much more efficient to keep track of the amount of added & removed nodes during the rewrite. The tracking doesn't need to be fully accurate, just enough to detect unbounded growth, so it should be very easy to implement!

2023-11-22 17:05 UTC, systay commented
> I think we need to look at benchmarks for this @systay, the O complexity of this new code is pathological 

Yeah, you are right. This was sloppy. I'll work on it

2023-11-23 08:01 UTC, vmg approved these changes
aaaah linear time

![image](https://github.com/vitessio/vitess/assets/42793/3a29a8b3-af88-4c81-8acd-5d45050f185d)

2023-11-23 08:01 UTC, vmg commented on go/vt/sqlparser/predicate_rewriting.go
> +		initialSize: initialSize,
I don't think this field is being used.

2023-11-23 08:01 UTC, vmg commented on go/vt/sqlparser/predicate_rewriting_test.go
> +				initialSize: 1000000000,
`math.MaxInt`? :smile:

2023-11-23 09:27 UTC, arthurschreiber commented on go/vt/sqlparser/predicate_rewriting.go
> +	// This loop can in some cases of this conversion to CNF can lead to an exponential explosion of the formula,
Something's off with this comment 😬

2023-11-23 10:20 UTC, dbussink approved these changes

2023-11-23 10:20 UTC, merged