Added unit tests for the constants/sidecar package
vitessio/vitess pull request #15044
Opened 2024-01-26 09:05 UTC by VaibhavMalik4187

## Description
This commit increases the code coverage of the `go/constants` package to 100%

## Related Issue(s)
Partially addresses: https://github.com/vitessio/vitess/issues/14931

## Checklist

-   [ ] "Backport to:" labels have been added if this change should be back-ported to release branches
-   [ ] If this change is to be back-ported to previous releases, a justification is included in the PR description
-   [x] Tests were added or are not required
-   [x] Did the new or modified tests pass consistently locally and on CI?
-   [ ] Documentation was added or is not required

2024-01-26 09:06 UTC, VaibhavMalik4187 commented
@GuptaManan100, could you please review this PR whenever you have a moment? Thanks!

2024-01-26 14:26 UTC, dbussink commented
I don't think adding tests for this is useful in any way. It merely adds overhead by now having to change these twice if we have to.

2024-01-26 18:52 UTC, mattlord approved these changes
Thanks, @VaibhavMalik4187 ! While I don't necessarily disagree with @dbussink, this does prevent us from *accidentally* changing the default (unlikely, but still) and if we do then it's not difficult to find and change this other location.

2024-01-26 18:57 UTC, VaibhavMalik4187 commented
> Thanks, @VaibhavMalik4187 ! While I don't necessarily disagree with @dbussink, this does prevent us from _accidentally_ changing the default (unlikely, but still) and if we do then it's not difficult to find and change this other location.

Now that I think about what @dbussink, it makes sense. However, I didn't pay much attention to these details when I wrote the tests. I was going through the codebase and was looking for packages lacking in tests, and that's when I thought of raising this small PR.

Thanks for reviewing this.

2024-01-29 11:00 UTC, GuptaManan100 requested changes
Whenever we change the global state in a test, we should ensure we set it back in a defer function call.

So, we should add this code to the test - 
```go
originalName := GetName()
defer func() {
    SetName(originalName)
}()
```

2024-02-04 06:58 UTC, GuptaManan100 commented
After recent discussion, we have decided not to merge tests that we don't find useful.

2024-02-04 06:58 UTC, closed without merging