Added missing tests for the go/streamlog package
vitessio/vitess pull request #15064
Opened 2024-01-28 19:42 UTC by VaibhavMalik4187

## Description
This commit increased the code coverage of the `go/streamlog` package to 93%.

## Related Issue(s)
Partially addresses: https://github.com/vitessio/vitess/issues/14931

## Checklist

-   [ ] "Backport to:" labels have been added if this change should be back-ported to release branches
-   [ ] If this change is to be back-ported to previous releases, a justification is included in the PR description
-   [x] Tests were added or are not required
-   [x] Did the new or modified tests pass consistently locally and on CI?
-   [ ] Documentation was added or is not required

2024-01-29 11:18 UTC, GuptaManan100 requested changes
The following change has to be made to the tests.

2024-01-29 11:18 UTC, GuptaManan100 commented on go/streamlog/streamlog_test.go
> +	SetRedactDebugUIQueries(false)
Whenever we change the global state in a test, we should ensure we set it back in a defer function call.

So, we should add this code to the test -

```go
originalVal := GetRedactDebugUIQueries()
defer func() {
    SetRedactDebugUIQueries(originalVal)
}()
```

We should do this for all the tests that change any state.

2024-02-04 07:01 UTC, GuptaManan100 reviewed
`TestRegisterStreamLogFlags` and `TestSetAndGetMethods` don't seem very useful. Please remove those two tests, and we can merge the remaining two.

2024-02-04 09:10 UTC, VaibhavMalik4187 commented
> `TestRegisterStreamLogFlags` and `TestSetAndGetMethods` don't seem very useful. Please remove those two tests, and we can merge the remaining two.

Alright, I'll update the code soon.

2024-02-04 19:34 UTC, VaibhavMalik4187 commented
> `TestSetAndGetMethods`

Done

2024-02-07 14:39 UTC, GuptaManan100 approved these changes

2024-02-13 10:02 UTC, harshit-gangal approved these changes

2024-02-13 10:02 UTC, merged