MySQL errors: `ERInnodbIndexCorrupt`
vitessio/vitess pull request #16851
Opened 2024-09-26 13:06 UTC by shlomi-noach

## Description

Add `ERInnodbIndexCorrupt` (error 1817) to the list of known MySQL errors. This can be used in the future to recognize terminal `ApplySchema` or Online DDL scenarios.

## Related Issue(s)

none

## Checklist

-   [ ] "Backport to:" labels have been added if this change should be back-ported to release branches
-   [ ] If this change is to be back-ported to previous releases, a justification is included in the PR description
-   [ ] Tests were added or are not required
-   [ ] Did the new or modified tests pass consistently locally and on CI?
-   [ ] Documentation was added or is not required

## Deployment Notes

2024-09-27 07:56 UTC, vmg approved these changes

2024-09-27 08:33 UTC, harshit-gangal requested changes
We should use this in 
go/vt/vttablet/tabletserver/tabletserver.go to convert from mysql error code to vitess error.

2024-09-29 06:16 UTC, shlomi-noach commented
> We should use this in `convertErrorCode`

@harshit-gangal done.

2024-09-30 11:48 UTC, harshit-gangal commented on go/vt/vttablet/tabletserver/tabletserver.go
>  	case sqlerror.EROptionPreventsStatement:
This got added under Internal Error in `constants` but used as `Failed_Precondition`.
```
// internal
	ERInternalError = ErrorCode(1815)
	ERInternalError      = ErrorCode(1815)
	ERInnodbIndexCorrupt = ErrorCode(1817)
```

We should align them.

2024-10-01 20:54 UTC, timvaillancourt approved these changes

2024-10-06 07:09 UTC, merged