Rewrite more queries
vitessio/vitess pull request #6831
Opened 2020-10-07 11:03 UTC by systay

This PR adds logic to handle subquery expressions that are not really needed.

If a query contains a SELECT expression looking something like:

```
SELECT * FROM user WHERE col = (SELECT 42)
```

this PR will unnest that subquery so that the query that is planned is instead:

```
SELECT * FROM user WHERE col = 42
```

Fixes #6827

2020-10-07 12:26 UTC, harshit-gangal approved these changes

2020-10-08 05:36 UTC, GuptaManan100 approved these changes
LGTM

2020-10-08 06:17 UTC, harshit-gangal requested changes
As I approved this earlier, making this as blocking so that I understand the change before merging.

2020-10-08 06:17 UTC, harshit-gangal commented on go/vt/vtgate/executor_select_test.go
>  	}}
expected sql query looks wrong to me
this should be `select :__lastInsertId as x from dual`

2020-10-08 06:25 UTC, harshit-gangal approved these changes
I looked as old commit. Ignore my previous comment.
One comment on test expectations.

2020-10-08 06:25 UTC, harshit-gangal commented on go/vt/vtgate/executor_select_test.go
>  }
1. This test does not require sbc1.SetResults as it does not go to sandbox connections.
1. Validate the query result of executed query it should match what is there in the session lastInsertId

2020-10-11 18:03 UTC, merged