Create pull_request_template
vitessio/vitess pull request #7027
Opened 2020-11-12 11:34 UTC by askdba

This is the first draft version of the pull request template.

2020-11-12 13:30 UTC, shlomi-noach requested changes
Thanks for working on this @askdba ! I've listed some thoughts and changes.


let's move the file to `.github/PULL_REQUEST_TEMPLATE`

2020-11-12 13:30 UTC, shlomi-noach commented on pull_request_template
> +**READY/IN DEVELOPMENT/HOLD**
I'd like to suggest we use the formal "draft pull request" to indicate that a pull request is not ready; and other wise the popular convention of "WIP" in the title.

2020-11-12 13:30 UTC, shlomi-noach commented on pull_request_template
> +## Description
Let's make this the very first section.

2020-11-12 13:30 UTC, shlomi-noach commented on pull_request_template
> +## Related PRs
Let's change that to "Related Issue(s)" - we've already decided during our 1st retrospective that each PR must be associated with an issue.

2020-11-12 13:30 UTC, shlomi-noach commented on pull_request_template
> +vitessio/vitess [link]()
IMO there is no need for this. You just put the link to an issue or PR and GitHub markdown automatically turns it into a link, with hover hints.

2020-11-12 13:30 UTC, shlomi-noach commented on pull_request_template
> +- [ ] Documentation
:+1:

2020-11-12 13:30 UTC, shlomi-noach commented on pull_request_template
> +vitessio/vitess [link]()
So, to clarify, the user will just put some links. Or even just `#34` -- GitHub will turn that into the correct link to issue 34.

2020-11-12 13:30 UTC, shlomi-noach commented on pull_request_template
> +Outline the steps to test or reproduce the PR here.
reproduction is for bugs, not for PRs, I think we should remove this section.

2020-11-16 09:33 UTC, shlomi-noach commented on .github/PULL_REQUEST_TEMPLATE
> +* Build
```suggestion
- [ ] Query Serving
- [ ] VReplication
- [ ] Cluster Management
- [ ] Build 
```

2020-11-16 09:38 UTC, shlomi-noach approved these changes

2020-11-16 16:27 UTC, deepthi requested changes

2020-11-16 16:27 UTC, deepthi commented on .github/PULL_REQUEST_TEMPLATE
> +Notes regarding deployment the contained body of work.  These should note any
```suggestion
Notes regarding deployment of the contained body of work.  These should note any
```

2020-11-16 19:31 UTC, deepthi approved these changes

2020-11-16 22:46 UTC, merged