[reparentutil] ERS should remove currently-serving shard primary from consideration
vitessio/vitess pull request #7523
Opened 2021-02-19 21:47 UTC by ajm188

## Description

This was in the old implementation, and was overlooked in the port to an
encapsulated struct. I've added tests as penance.

Signed-off-by: Andrew Mason <amason@slack-corp.com>

## Related Issue(s)

- #7464 

## Checklist
- [ ] Should this PR be backported? **no** (#7464 isn't released, so no need to backport)
- [x] Tests were added or are not required
- [x] Documentation was added or is not required

## Deployment Notes

## Impacted Areas in Vitess
Components that this PR will affect:

- [ ]  Query Serving
- [ ]  VReplication
- [x]  Cluster Management
- [ ]  Build/CI
- [ ]  VTAdmin

2021-02-19 22:45 UTC, setassociative commented
@ajm188 before digging into this are the unit test failures concerning? They feel topical given it's testing ERS

```
--- FAIL: TestEmergencyReparentShard (0.01s)
Error:     vtctl_pipe.go:100: I0219 21:58:20.139131 emergency_reparenter.go:311] deleting old primary%!(EXTRA string=cell1-0000000000)
Error:     vtctl_pipe.go:100: I0219 21:58:20.139239 replication.go:181] getting replication position from cell2-0000000003
Error:     vtctl_pipe.go:100: I0219 21:58:20.139326 replication.go:181] getting replication position from cell1-0000000001
Error:     vtctl_pipe.go:100: I0219 21:58:20.139380 replication.go:181] getting replication position from cell1-0000000002
Error:     vtctl_pipe.go:100: W0219 21:58:20.140640 replication.go:205] failed to get replication status from cell1-0000000001: rpc error: code = Canceled desc = context canceled
```

2021-02-19 23:55 UTC, ajm188 commented
It's definitely worth looking into those, but they _may_ be red herrings:

```
I0219 21:54:03.947626   16521 vtctlclient_process.go:149] Executing vtctlclient with command: vtctlclient -server localhost:16806 EmergencyReparentShard -keyspace_shard ks/0 -wait_replicas_timeout 30s
    reparent_test.go:137: 
        	Error Trace:	reparent_test.go:137
        	Error:      	Expected value not to be nil.
        	Test:       	TestReparentIgnoreReplicas
        	Messages:   	W0219 21:54:03.965804   28276 main.go:67] W0219 21:54:03.965656 replication.go:205] failed to get replication status from zone1-0000000103: rpc error: code = Canceled desc = latest connection error: connection error: desc = "transport: Error while dialing dial tcp :0: connect: connection refused"
--- FAIL: TestReparentIgnoreReplicas (50.45s)
```

2021-02-20 03:23 UTC, ajm188 commented
Hmmm, @setassociative looking again at #7464, in particular [here](https://github.com/vitessio/vitess/pull/7464/files#diff-983eff6b8bfd3a97372e82113615c6c4dd9162eb340b9dbbf438a4ccc28e0b15L568-L624), it seems this block I've added actually didn't exist anymore, and was removed in [6449](https://github.com/vitessio/vitess/pull/6449/files#diff-983eff6b8bfd3a97372e82113615c6c4dd9162eb340b9dbbf438a4ccc28e0b15L879-L916) (I was looking at `tinyspeck/master` and not `vitessio` just prior to my first refactor).

Anyway, the reason that I noticed this, was when writing tests for adding ERS to the new `VtctldServer` API, if I tried to ERS with a reachable shard primary, then I get a segfault on `nil` pointer. The reason here is that [first we construct two maps](
https://github.com/vitessio/vitess/blob/4e646441d5bb62d7cf4a5c550e13df5350dd8dd5/go/vt/vtctl/reparentutil/emergency_reparenter.go#L280), `statusMap`, which is a mapping of `tablet alias -> StopReplicationStatus` for all the replicas in the shard, and `primaryStatusMap`, which is a mapping of `tablet alias -> MasterStatus` for any tablets that claim to be MASTER, but pass only the `statusMap` through to [`waitForAllRelayLogsToApply`](https://github.com/vitessio/vitess/blob/4e646441d5bb62d7cf4a5c550e13df5350dd8dd5/go/vt/vtctl/reparentutil/emergency_reparenter.go#L297), which results in a `nil` `Status` when we eventually call [`WaitForRelayLogsToApply`](https://github.com/vitessio/vitess/blob/4e646441d5bb62d7cf4a5c550e13df5350dd8dd5/go/vt/vtctl/reparentutil/emergency_reparenter.go#L358). This was true prior to my refactor as best as I can tell.

I'm confident this is the "issue" I saw, but I'm not confident it's actual issue vs me accidentally creating an impossible situation in my test setup (but we should add a guard against nil input so we don't segfault during ERS either way), or how to best handle this. I _think_ what we actually want is to just skip the MASTERs, because they aren't applying relay logs since they are not replicating, so something like:

```go
func (erp *EmergencyReparnter) waitForAllRelayLogsToApply(/* blah blah blah */) (/* blah blah*/) {
	errCh := make(chan error)
	defer close(errCh)

	groupCtx, groupCancel := context.WithTimeout(ctx, opts.WaitReplicasTimeout)
	defer groupCancel()

	replicaCount := 0

	for candidate := range validCandidates {
		tablet, ok := tabletMap[candidate]
		// handle !ok and return error
		if tablet.Type == topodatapb.TabletType_MASTER {
			// log
			continue
		}

		go func(alias string) {
			var err error
			defer func() { errCh <- err }()
			err = WaitForRelayLogsToApply(groupCtx, erp.tmc, tabletMap[alias], statusMap[alias])
		}(candidate)

		replicaCount++
	}

	errgroup := concurrency.ErrorGroup{
		NumGoroutines:                replicaCount,
		NumRequiredSuccesses: replicaCount,
		NumAllowedErrors:           0,
	}
	rec := errgroup.Wait(groupCancel, errCh)

	// rest of the function unchanged
}
```

cc @deepthi @PrismaPhonic to double-check my read here

2021-02-20 04:52 UTC, PrismaPhonic commented
The design is VERY intentional upon not assuming who masters are. This allows us to handle a host of edge cases where a tablet thinks it's master when it's really not.

2021-02-20 04:53 UTC, PrismaPhonic requested changes
I'm blocking on this until we can discuss it further, because it pushes against the design by trying to know who the master is. That was a very important part of our re-design (to intentionally not try to assume who the master was)

2021-02-20 12:58 UTC, ajm188 commented
I am well aware of that design consideration. In my most recent comment, I point out that the change currently in this PR is not the change we want:

> it seems this block I've added actually didn't exist anymore, and was removed in [6449](https://github.com/vitessio/vitess/pull/6449/files#diff-983eff6b8bfd3a97372e82113615c6c4dd9162eb340b9dbbf438a4ccc28e0b15L879-L916)  (I was looking at tinyspeck/master and not vitessio just prior to my first refactor).

The actual issue, as I attempted to describe in my most recent comment, is that a MASTER tablet will return `mysql.ErrNotReplica` from `tmc.StopReplicationAndGetStatus`, which will cause us to add an entry for that tablet in the `primaryStatusMap` and not the `statusMap`, in [`StopReplicationAndBuildStatusMap`](https://github.com/vitessio/vitess/blob/4e646441d5bb62d7cf4a5c550e13df5350dd8dd5/go/vt/vtctl/reparentutil/replication.go#L185-L199). _Then_, when we attempt to wait for all valid candidates to apply their relay logs (which can include MASTER tablets), we end up passing a nil Status to [`WaitForRelayLogsToApply`](https://github.com/vitessio/vitess/blob/4e646441d5bb62d7cf4a5c550e13df5350dd8dd5/go/vt/vtctl/reparentutil/emergency_reparenter.go#L358), causing the segfault.

I agree that not making assumptions about who the primary is remains an important aspect of the design, but this needs to be fixed, as crashing during an ERS is also quite dangerous to health of the cluster the ERS is trying to salvage.

2021-02-20 21:04 UTC, ajm188 commented
I've pushed, in order:
1. A revert of the original change
2. A minimal test case that caused the panic, to demonstrate the problem we are trying to solve here.
3. A fix for that test case, with commentary.

Assuming we're all on board with this, I'll update the PR description and dig in to any other tests that broke as a result.

2021-02-22 20:27 UTC, deepthi commented
@ajm188 can you update the title and description of the PR to better reflect the changes? Thanks!

2021-02-24 18:51 UTC, PrismaPhonic approved these changes
This looks like a much better approach. Thank you!

2021-02-24 19:27 UTC, merged