correct several wrong words
vitessio/vitess pull request #7822
Opened 2021-04-12 01:16 UTC by zhangshj-inspur

correct several wrong words

2021-04-12 23:00 UTC, deepthi approved these changes

2021-04-12 23:01 UTC, deepthi requested changes
Thank you for the contribution!
Can you please fix the DCO check that is failing?

2021-04-13 02:20 UTC, zhangshj-inspur commented
> Thank you for the contribution!
> Can you please fix the DCO check that is failing?

I already amend it wtih the option --signoff,guess fix it.

2021-04-13 18:26 UTC, deepthi approved these changes

2021-04-14 23:21 UTC, merged