Add VtctldServer to vtcombo
vitessio/vitess pull request #7896
Opened 2021-04-19 20:28 UTC by ajm188

Signed-off-by: Andrew Mason <amason@slack-corp.com>

## Description

### Testing

1. build and run vttestserver: `make build; ./bin/vttestserver`
2. get gRPC port: `sudo lsof -iTCP -P -sTCP:LISTEN | grep vtcombo | awk '{print $9}' | sort | head -n 2 | head -n 1 | sed 's/.*://'`
3. run client:
```
❯ ./bin/vtctldclient --server "localhost:12592" GetKeyspaces
[
  {
    "name": "test_keyspace",
    "keyspace": {}
  }
]
```

## Related Issue(s)

- Closes #7894 

## Checklist
- [ ] Should this PR be backported? **no**
- [ ] Tests were added or are not required **n/a**
- [ ] Documentation was added or is not required **n/a**

## Deployment Notes

## Impacted Areas in Vitess
Components that this PR will affect:

- [ ]  Query Serving
- [ ]  VReplication
- [x]  Cluster Management
- [ ]  Build/CI
- [ ]  VTAdmin

2021-04-19 21:04 UTC, deepthi requested changes
LGTM, but needs a unit test.

2021-04-20 13:11 UTC, acharisshopify commented
thanks, man

2021-04-20 16:29 UTC, deepthi approved these changes

2021-04-20 16:29 UTC, deepthi commented on go/vt/vttest/environment_test.go
> +		require.Contains(t, args, "-service_map", "vttest.LocalTestEnv must contain provide `-service_map` flag to vtcombo")
nit: I'm guessing this was intended to be
`must provide ...`
not
`must contain provide ...`

2021-04-23 18:53 UTC, merged