Signed int parse
vitessio/vitess pull request #8189
Opened 2021-05-25 13:08 UTC by GuptaManan100

## Description
The following query does not work correctly in the parser
```sql
alter table t add column iii int signed not null;
```
This PR fixes it by adding the optional SIGNED token after the numeric type names.

## Related Issue(s)
Fixes #8153 

## Checklist
- [x] Tests were added or are not required
- [x] Documentation was added or is not required

2021-05-25 14:34 UTC, shlomi-noach commented
Does this need support in `ast_print.go`?

2021-05-26 18:02 UTC, systay requested changes
We should not drop the signed/unsigned part in the AST

2021-05-27 10:12 UTC, GuptaManan100 commented
We are already storing the signed/unsigned part in the AST. Its just that signed is the default so it is dropped. Since we already had the functionality of storing this in AST, we do not require any changes to `ast_format.go`. I have added a test which checks that we indeed do not ignore `unsigned`.

2021-05-27 11:54 UTC, shlomi-noach approved these changes
sounds good

2021-05-27 12:39 UTC, systay approved these changes

2021-05-27 12:39 UTC, merged