[parser] use table_alias for ENGINE option in CREATE TABLE stmt
vitessio/vitess pull request #8307
Opened 2021-06-10 20:36 UTC by acharisshopify

fixes: https://github.com/vitessio/vitess/issues/8241

Signed-off-by: Alex Charis <alex.charis@shopify.com>

## Description
The program attached to the linked issue now outputs:
```
&{false {foo } false 0xc000120480 <nil> [] true} <nil>
&{false {foo } false 0xc000120600 <nil> [] true} <nil>
&{false {foo } false 0xc000120780 <nil> [] true} <nil>
```

## Checklist
- [X] Tests were added or are not required
- [X] Documentation was added or is not required

2021-06-11 04:38 UTC, GuptaManan100 approved these changes
LGTM 💕

2021-06-14 06:35 UTC, harshit-gangal requested changes
changes look good. A test is needed for it to merge.

2021-06-15 11:01 UTC, systay approved these changes

2021-06-15 12:10 UTC, harshit-gangal approved these changes

2021-06-15 12:10 UTC, merged