run xtrabackup with --lock-ddl-per-table
vitessio/vitess pull request #8317
Opened 2021-06-11 20:52 UTC by deepthi

## Description

Some of the backup/restore tests have been flaky for a while. Today @vmg was able to extract the actual error from a failing test.
This seems to be a known issue with a documented workaround. Implementing the workaround.
https://www.percona.com/blog/2017/08/08/avoiding-the-an-optimized-without-redo-logging-ddloperation-has-been-performed-error-with-percona-xtrabackup/

This is the minimal safe change, because we only change the test options and no actual code for anyone else.
However, we should evaluate whether to always run xtrabackup with either `--lock-ddl`  or `--local-ddl-per-table`.

## Related Issue(s)
#8315 

## Checklist
- [x] Tests were added or are not required
- [x] Documentation was added or is not required

## Deployment Notes

2021-06-12 01:00 UTC, aquarapid approved these changes
Do we also want to put a note somewhere in https://vitess.io/docs/user-guides/operating-vitess/backup-and-restore/creating-a-backup/ ?

2021-06-14 05:17 UTC, systay requested changes
Lets make sure this should not go into an earlier branch first

2021-06-14 07:57 UTC, shlomi-noach commented
Noting that enabling `--old_alter_table` effectively disables concurrent DML on table while `ALTER TABLE` takes place. We do happen to offer Online DDL in vitess, but users who will run `direct` `ALTER TABLE` and with `ALGORITHM=INPLACE LOCK=NONE` may be surprised by this change of behavior.

2021-06-14 15:04 UTC, vmg commented
@shlomi-noach afaict this change of behavior is only on the end-to-end tests and doesn't apply to normal production usage.

2021-06-15 05:04 UTC, shlomi-noach commented
> this change of behavior is only on the end-to-end tests

Ah, then please just ignore me.

2021-06-15 10:23 UTC, systay approved these changes

2021-06-15 10:38 UTC, shlomi-noach commented
Gonna resubmit these changes into `release-9.0`

2021-06-15 10:53 UTC, shlomi-noach commented
Resubmitted against `release-9.0`: https://github.com/vitessio/vitess/pull/8340

2021-06-15 10:56 UTC, closed without merging

2021-06-15 10:56 UTC, systay commented
Closing so we don't accidentally hit that big green button