resolve parser conflicts and add keyword compatibility test case
vitessio/vitess pull request #8395
Opened 2021-06-29 01:48 UTC by longfei-not-bot

Signed-off-by: longfei <lf.x.0720@gmail.com>

## Description

1. fix conflicts in parser
2. add some Identifier to non_reserved_keyword

## Related Issue(s)

Fixes #8358

## Checklist
- [x] Tests were added or are not required
- [ ] Documentation was added or is not required

## Deployment Notes

2021-06-29 03:53 UTC, GuptaManan100 requested changes
Could you also add tests for the changes you made to the parser. We already had the correct parsing of `UNIQUE KEY` because shift/reduce conflicts resolve to shifting. Also I am not sure what replacing `table_id_opt` is accomplishing. The tests for the parser live in `go/vt/schema/parser_test.go`

2021-06-30 05:19 UTC, GuptaManan100 commented
Yes, you are right, it is `go/vt/sqlparser/parser_test.go`. Could you add tests for this change there? Also, you should run `make parser` to regenerate the `sql.go` file since the test `check_make_parser` is failing

2021-06-30 09:10 UTC, GuptaManan100 approved these changes
This looks amazing to me! Also verified that MySQL handles `UNIQUE KEY` exactly as proposed in this PR. Thank you for contributing to Vitess! 🐎  😃

2021-07-05 06:35 UTC, harshit-gangal approved these changes

2021-07-05 06:35 UTC, merged