Increase replication pos column size
vitessio/vitess pull request #8613
Opened 2021-08-09 22:53 UTC by gtowey

## Description

This change fixes errors using vreplication when the gtid_executed set is very large.  

This can happen as part of normal MySQL server operation if there simply happens to be many changes in primary instances in a cluster.  There doesn't seem to be any defined maximum size on the string values returned so it's critical that larger values are handled.  The column type has been changed from varbinary to blob because larger varbinary values cause an error when the maximum row size for the table exceeds 64k

## Related Issue(s)
https://github.com/vitessio/vitess/issues/8612

## Checklist
- [ ] Should this PR be backported?
- [ ] Tests were added or are not required
- [ ] Documentation was added or is not required

2021-08-10 20:22 UTC, deepthi commented on go/vt/binlog/binlogplayer/binlog_player.go
> +  pos BLOB NOT NULL,
In order for in-place upgrades to also get the new column definition, we need to add an `ALTER TABLE ... MODIFY ...`
(lines 561-566).
I see we did that for `source` but not sure why the definition here still says `VARBINARY`.

2021-08-11 16:44 UTC, deepthi commented
Can you fix the DCO? Once this is ready for review we can run CI.

2021-08-12 08:30 UTC, rohit-nayak-ps requested changes
Thanks for the PR. CI actions have been enabled.

As @deepthi noted, we should use the ALTER approach so that existing installations are also upgraded with this change.

You should add to the alter DDL list at `go/vt/binlog/binlogplayer/binlog_player.go:561` and also to the test ddls list at `go/vt/vttablet/tabletmanager/vreplication/engine_test.go:498`. 

This PR does a similar thing: https://github.com/vitessio/vitess/pull/6421

We also have a feature to compress the pos before storing: https://github.com/vitessio/vitess/pull/7877. Since you have large GTIDs you may want encounter similar issues described here.

2022-06-15 00:23 UTC, mattlord commented
I'm closing this for now as it appears to have gone stale and I believe the underlying issue has been addressed.

Please let me know if I missed or misunderstood something and we can re-open it. Thanks!

2022-06-15 00:23 UTC, closed without merging