Add enable_system_settings flag change to 12.0.0 release summary
vitessio/vitess pull request #9144
Opened 2021-11-04 14:30 UTC by askdba

Signed-off-by: Alkin Tezuysal <alkin.tezuysal@gmail.com>

## Description
Add information regarding default flag change of `enable_system_settings` 

## Related Issue(s)
https://github.com/vitessio/website/pull/862

## Checklist
- [ ] Should this PR be backported?
- [ ] Tests were added or are not required
- [ ] Documentation was added or is not required

## Deployment Notes

2021-11-04 15:55 UTC, hallaroo requested changes

2021-11-04 15:55 UTC, hallaroo commented on doc/releasenotes/12_0_0_summary.md
>  Use of reserved connections are controlled by the vtgate flag `-enable_system_settings`. This flag has traditionally defaulted to false (or off) in release versions (i.e. x.0 and x.0.y) of Vitess, an
I think we need to add this to the end: From Vitess 12.0 onwards, it defaults to true in all release and development versions.

2021-11-05 04:46 UTC, askdba reviewed
LGTM

2021-11-08 09:31 UTC, askdba reviewed
LGTM

2021-11-08 09:32 UTC, askdba reviewed
LGTM

2021-11-08 15:36 UTC, hallaroo approved these changes
LGTM

2021-11-08 15:36 UTC, merged