changing -dry-run to -dry_run
vitessio/vitess pull request #9250
Opened 2021-11-16 23:30 UTC by hallaroo

Signed-off-by: hallaroo 

## Description
@aquarapid found a couple places in the help where [-dry_run] was replaced with [-dry-run]. This PR changes this back as [-dry-run] is not the correct usage, it should be the underscore one.

e.g.:

`SwitchReads Error: rpc error: code = Unknown desc = flag provided but not defined: -dry-run
E1116 15:14:07.388982   98844 main.go:76] remote error: rpc error: code = Unknown desc = flag provided but not defined: -dry-run
`

## Related Issue(s)
Not 100% sure when this was introduced but found the same issue in https://github.com/vitessio/vitess/pull/9177/ 

## Checklist
- [ ] Should this PR be backported?
- [ - ] Tests were added or are not required
- [ - ] Documentation was added or is not required

2021-11-17 02:27 UTC, deepthi requested changes
I looked through the history of the file, and only two of the changes are needed.
The others are consistent between the help and actual command syntax, so should stay the same.
It is unfortunate that the earlier commands used hyphens but the newer ones use underscores (and have already been deprecated).

2021-11-17 02:27 UTC, deepthi commented on go/vt/vtctl/vtctl.go
> +				params: "[-dry_run] <tablet alias> <tablet type>",
Should be reverted

2021-11-17 02:27 UTC, deepthi commented on go/vt/vtctl/vtctl.go
> +				params: "[-cells=c1,c2,...] [-reverse] -tablet_type={replica|rdonly} [-dry_run] <keyspace.workflow>",
:heavy_check_mark:

2021-11-17 02:27 UTC, deepthi commented on go/vt/vtctl/vtctl.go
> +				params: "[-timeout=30s] [-reverse] [-reverse_replication=true] [-dry_run] <keyspace.workflow>",
:heavy_check_mark:

2021-11-17 02:27 UTC, deepthi commented on go/vt/vtctl/vtctl.go
> +				params: "{-vschema=<vschema> || -vschema_file=<vschema file> || -sql=<sql> || -sql_file=<sql file>} [-cells=c1,c2,...] [-skip_rebuild] [-dry_run] <keyspace>",
Should be reverted

2021-11-17 02:27 UTC, deepthi commented on go/vt/vtctl/vtctl.go
> +				params: "{-rules=<rules> || -rules_file=<rules_file>} [-cells=c1,c2,...] [-skip_rebuild] [-dry_run]",
Should be reverted

2021-11-18 13:17 UTC, ajm188 reviewed
any reason we don't just switch all these to `DualFormatStringVar`? https://github.com/vitessio/vitess/blob/main/go/flagutil/flagutil.go#L140-L149

2021-11-18 20:41 UTC, hallaroo commented
> any reason we don't just switch all these to `DualFormatStringVar`? https://github.com/vitessio/vitess/blob/main/go/flagutil/flagutil.go#L140-L149

Just to get the help changed out would you be willing to move this to be its own issue? Or let me know and I can get one added. Thanks!

2021-11-21 13:39 UTC, deepthi commented
> any reason we don't just switch all these to `DualFormatStringVar`? https://github.com/vitessio/vitess/blob/main/go/flagutil/flagutil.go#L140-L149

No reason not to, but let's make that a separate task and not block this PR.

2021-11-21 13:40 UTC, deepthi approved these changes

2021-11-21 13:40 UTC, merged