evalengine: Fuzz!
vitessio/vitess pull request #9310
Opened 2021-12-01 14:08 UTC by vmg

## Description

As explained previously to @frouioui @systay and @GuptaManan100, I've implemented a simple fuzzer for the evaluation engine that generates random expressions and compares their evaluation result's against MySQL's to see if we're being consistent.

It resulted in a _lot_ of small fixes, which have been implemented in this branch. The most significant one, which is not small at all, is the introduction of a `decimal` package to handle decimal precision numbers. We're using a fork of https://github.com/ericlagergren/decimal (which is license compatible with Vitess) with several small changes to make it behave closer to how the decimal implementation works in MySQL. In order to simplify integration and development, the relevant parts of the library (i.e. the functionality we use) has been vendored inside the `evalengine` package.
 
I'm going to keep pushing a few more bug fixes to this branch for the remaining issues found by the fuzzer.

## Related Issue(s)

## Checklist
- [ ] Should this PR be backported?
- [x] Tests were added or are not required
- [x] Documentation was added or is not required

## Deployment Notes

2021-12-06 11:48 UTC, frouioui approved these changes
I love it! thank you @vmg, looks good to me. I will take care of dealing with the few comments I left

2021-12-06 11:48 UTC, frouioui commented on go/sqltypes/bind_variables.go
> +type DecimalFloat float64
I think this should live at the top of the file

2021-12-06 11:48 UTC, frouioui commented on go/vt/vtgate/evalengine/comparisons.go
> +func evalCompare(lVal, rVal EvalResult) (comp int, isNull bool, err error) {
We should rename this to `evalCompareAll` as it compares all types of `EvalResult` (tuples, non-tuples, nulls)

2021-12-06 11:48 UTC, frouioui commented on go/vt/vtgate/evalengine/comparisons.go
> +func evalCompare1(lVal, rVal EvalResult) (comp int, err error) {
once the above method `evalCompare` is renamed, we can rename this to `evalCompare`

2021-12-06 11:48 UTC, frouioui commented on go/vt/vtgate/evalengine/comparisons.go
>  	}
the else statement can be omitted

2021-12-06 11:48 UTC, frouioui commented on go/vt/vtgate/evalengine/mysql_test.go
> +
Add header

2021-12-06 11:48 UTC, frouioui commented on go/vt/vtgate/evalengine/integration/fuzz_test.go
> +
Add header

2021-12-06 11:48 UTC, frouioui commented on go/vt/vtgate/evalengine/integration/fuzz_test.go
> +type dummyCollation collations.ID
lets move these at the top of the file

2021-12-06 11:48 UTC, frouioui commented on go/vt/vtgate/evalengine/integration/main_test.go
> +../../../../mysql/collations/integration/main_test.go
@vmg, is this a way to import the content of `mysql/collations/integration/main_test.go` to this file?

2021-12-06 18:18 UTC, frouioui requested changes

2021-12-06 18:18 UTC, frouioui commented on go/vt/vtgate/evalengine/integration/fuzz_test.go
> +}
This needs to be changed

2021-12-06 18:28 UTC, frouioui commented on go/vt/vtgate/evalengine/integration/fuzz_test.go
> +}
@vmg, I removed the test via 1c2ef13

2021-12-06 18:32 UTC, frouioui reviewed
The evalengine's fuzzer is failing on my side when I run it using MySQL80. Here is a snippet of the failures:
```
mismatch for query "SELECT 0 NOT LIKE \"foo\"": local=UINT64(1), remote=INT64(1)
mismatch for query "SELECT NULL NOT LIKE \"FOO\"": local=UINT64(1), remote=NULL
mismatch for query "SELECT -1 = \"fOo\"": local=UINT64(0), remote=INT64(0)
mismatch for query "SELECT 1 <=> 1": local=UINT64(1), remote=INT64(1)
```

It seems that we are returning different types than what MySQL80 does

2021-12-08 12:55 UTC, systay commented
out of interest - why fork https://github.com/ericlagergren/decimal instead of contributing fixes and depending on it?

2021-12-08 15:44 UTC, AdamKorcz commented
Very cool. Would be great to get this running continuously on OSS-fuzz which would require a rewrite to go-fuzz or waiting until OSS-fuzz supports native fuzzing which will happen in 2022.

2021-12-09 10:31 UTC, vmg commented
> why fork https://github.com/ericlagergren/decimal instead of contributing fixes and depending on it?

I don't think the maintainer of that package will accept fixes that implement MySQL's specific behavior. The package implements the ISO decimal standard, and MySQL doesn't so...

2021-12-09 15:55 UTC, frouioui approved these changes
awesome work 🏆

2021-12-09 15:59 UTC, merged