Move more code to use evalengine
vitessio/vitess pull request #9351
Opened 2021-12-10 08:40 UTC by systay

Signed-off-by: Andres Taylor <andres@planetscale.com>

## Description

## Related Issue(s)

## Checklist
- [ ] Should this PR be backported?
- [ ] Tests were added or are not required
- [ ] Documentation was added or is not required

## Deployment Notes

2021-12-10 09:22 UTC, vmg requested changes

2021-12-10 09:22 UTC, vmg commented on go/vt/vtgate/evalengine/convert.go
> +		lit.Val.collation = collations.TypedCollation{
You should not override the whole `TypedCollation`, just assign to `lit.Val.collation.Collation` so it keeps the original coercibility. :ok_hand:

2021-12-10 11:20 UTC, vmg approved these changes

2021-12-13 10:38 UTC, frouioui approved these changes
awesome work, this is really exciting

2021-12-13 10:38 UTC, frouioui commented on go/vt/vtgate/engine/limit.go
> +		other["Offset"] = evalengine.FormatExpr(l.Offset)
It would be nicer to print the raw value instead of printing type+value, like: print `1` instead of `INT64(1)`

2021-12-14 07:05 UTC, harshit-gangal approved these changes

2021-12-14 08:21 UTC, merged