evalengine: support mysql floor func
vitessio/vitess pull request #9762
Opened 2022-02-23 02:51 UTC by MengJianGui

## Description

evalengine: Support built-in MySQL function FLOOR.
but I find some supported func eg.isnull(), not support expression 1/0.

## Related Issue(s)

Fixes #9647

## Checklist
- [ ] Should this PR be backported?
- [ ] Tests were added or are not required
- [ ] Documentation was added or is not required

## Deployment Notes

2022-02-23 13:59 UTC, vmg requested changes
Hi @MengJianGui! Thanks for your contribution! I left you some review feedback, particularly regarding the testing of the implementation. The functions in MySQL have a lot of corner cases and weird behaviors, so it's important you write an integration test like I pointed out that tries to floor as many different floats as you can think of. Cheers!

2022-02-23 13:59 UTC, vmg commented on go/vt/vtgate/evalengine/func.go
> +	thisF, err := args[0].Value().ToFloat64()
You're supposed to use `args[0].float64()` here.

2022-02-23 13:59 UTC, vmg commented on go/vt/vtgate/evalengine/func.go
> +	result.setInt64(int64(math.Floor(thisF)))
Are you sure this is the right return type?

2022-02-23 13:59 UTC, vmg commented on go/vt/vtgate/evalengine/integration/testdata/mysql_golden_1645577591.json
> +[
This is not the right way to test the feature -- the `mysql_golden` files are supposed to be generated by our fuzzer. To properly test the new implementation, you need to add a test to our `comparison_test.go` file that tests the `FLOOR` call with many different inputs.

Here's an example testing a similar function call:

https://github.com/vitessio/vitess/blob/main/go/vt/vtgate/evalengine/integration/comparison_test.go#L471-L498

2022-03-01 10:06 UTC, vmg commented on go/vt/vtgate/evalengine/func.go
> +	result.setString(val, collations.TypedCollation{
This is most definitely not the way to implement `FLOOR`, as it can never return a `VARCHAR` value. Have you actually ran the tests locally?

2022-03-02 09:21 UTC, vmg requested changes

2022-03-02 09:21 UTC, vmg commented on go/vt/vtgate/evalengine/integration/comparison_test.go
> +		compareRemoteQuery(t, conn, fmt.Sprintf(" SELECT FLOOR('%s')", number))
This integration test is broken: you're always wrapping the input to `FLOOR` with ticks, so you're always trying to floor string values. You need to remove those ticks (and place them in some of the values in the `numbers` slice) so you're actually flooring numbers. Then you'll see that your implementation is not correct for many different numeric types.

2022-03-29 07:26 UTC, systay commented
Hi @MengJianGui!

Are you still interested in merging this PR? I'm going over old PRs checking what we can close.

2022-08-17 01:42 UTC, closed without merging