evalengine builtin func: CEIL
vitessio/vitess pull request #9795
Opened 2022-02-28 01:16 UTC by Jin-2019

evalengine: Support all built-in MySQL functions CEIL

2022-02-28 12:49 UTC, frouioui requested changes
Hello @Jin-2019, thanks for your contribution! 🎉 

In order for the [DCO check](https://github.com/vitessio/vitess/pull/9795/checks?check_run_id=5353651422) to pass successfully, you will need to sign your commit by executing the following command within your forked repository:

```sh
git rebase HEAD~1 --signoff
git push --force-with-lease origin main
```

2022-02-28 14:52 UTC, vmg requested changes
Thanks for your first contribution to Vitess! The behavior of the function you've implemented is not quite right. Please double check it and improve the integration tests. Cheers!

2022-02-28 14:52 UTC, vmg commented on go/vt/vtgate/evalengine/integration/comparison_test.go
> +		"0", "1", "1.123", "-1.23", "NULL",
You're not testing this with any floating point numbers. Could you please add some here? There are also other interesting test cases, such as strings, larger decimals, decimals closer to the `.5` half in rounding, larger negative decimals, numbers that would upcast their type when ceiled, etc. Please be imaginative and try to add as many test cases as possible.

2022-03-29 07:25 UTC, systay commented
Hi @Jin-2019!

Are you still interested in merging this PR? I'm going over old PRs checking what we can close.

2022-08-16 01:36 UTC, closed without merging