Evalengine sign function
vitessio/vitess pull request #9799
Opened 2022-02-28 13:54 UTC by ABlueCy

## Description

## Related Issue(s)

## Checklist
- [ ] Should this PR be backported?
- [ ] Tests were added or are not required
- [ ] Documentation was added or is not required

## Deployment Notes

2022-02-28 15:32 UTC, vmg requested changes
Thanks for your first contribution to Vitess! I'm afraid that the logic for the `SIGN` built-in you've implemented is not quite correct. If you were to write some integration tests for the feature, particularly for comparing it against MySQL, you'd find that the function works with many numerical types, not just `float64`. Adding those tests to the PR will let you make sure that you're implementing the right functionality.

2022-02-28 15:32 UTC, vmg commented on go/vt/vtgate/evalengine/func.go
> +	if toSign.float64() > 0 {
What happens if `toSign` is not a `float64`? :)

2022-02-28 15:32 UTC, vmg commented on go/vt/vtgate/evalengine/func.go
> +	return args[0].typeof(env)
This can't possibly be right, as the return of the `SIGN` function is not related to the actual input argument.

2022-02-28 15:46 UTC, frouioui reviewed
Hello @ABlueCy and thank you for your contribution!

Can you please provide a more detailed description of your pull request?

2022-03-29 07:25 UTC, systay commented
Hi @ABlueCy!

Are you still interested in merging this PR? I'm going over old PRs checking what we can close.

2022-08-15 01:36 UTC, closed without merging